Add status bar item for JSON schema selection
redhat-developer/vscode-yaml pull request #643
Opened 2021-11-16 12:33 UTC by evidolob

### What does this PR do?
Add new status bar item in VSCode status bar. This status bar shows current schema used and allow to select/switch schema with UI (quick pick box). It also indicate with error background if yaml-ls uses more than one schema for file.

Demo:

https://user-images.githubusercontent.com/929743/141985832-d207df10-9a26-48c1-99cb-f9edd327180b.mov

Depends on https://github.com/redhat-developer/yaml-language-server/pull/556

### What issues does this PR fix or reference?

Resolve: redhat-developer/vscode-yaml#565

### Is it tested? How?
With test

2021-11-16 22:20 UTC, gorkem commented on src/schema-status-bar-item.ts
> +      statusBarItem.backgroundColor = new ThemeColor('statusBarItem.errorBackground');
Is this an error situation or a warning one? Should we use `warningBackground` instead?

2021-11-16 22:35 UTC, gorkem requested changes
The build seems to fail as well.

2021-11-16 22:35 UTC, gorkem commented on src/schema-status-bar-item.ts
> +      statusBarItem.text = 'Multiple JSON Schemas...'; //schema.map((val) => val.name ?? val.uri).join(' | ');
remove unused comment

2021-11-16 22:35 UTC, gorkem commented on src/schema-status-bar-item.ts
> +      if (typeof element === 'string') {
do you really need this  when the next if is strict equality?

2021-11-17 13:28 UTC, JPinkney approved these changes

2021-11-17 13:28 UTC, JPinkney commented on test/json-schema-selection.test.ts
> +describe('Completion should work in multiple different scenarios', () => {
```suggestion
describe('Status bar should work in multiple different scenarios', () => {
```

2021-11-20 18:21 UTC, gorkem requested changes
I suppose this should be tested together with https://github.com/redhat-developer/yaml-language-server/pull/556. However I have not been able to compile the project. When I trie the instructions on [CONTRIBUTING.md](https://github.com/redhat-developer/vscode-yaml/blob/main/CONTRIBUTING.md#developing-the-client-and-server-together) compilation fails. When I try to do `yarn link` compilation fails. At the moment, I can not test this change.

2021-11-23 13:47 UTC, evidolob commented
@gorkem Could you share errors which you have?

I try several times and all compilation pass for me.

Other problem with this PR that tests on CI is failing for some reasons, locally they pass. Going to investigate that.

2021-11-25 08:52 UTC, evidolob commented
@gorkem Now flow with `yarn link` should work, the problem was with replacement of `process` lib.

2021-11-25 15:42 UTC, gorkem approved these changes

2021-12-15 13:08 UTC, merged